{"uuid": "6d4ff94c-d646-4d15-a65a-d82cb49433c5", "children": ["4694c04e-3577-49a9-8a07-399c877c8f2d", "b4dc3dcf-7be8-44b0-9ed5-135febe025fa", "1dbfd3b9-b590-46b2-82bf-787a5470e28a", "01ab23b1-11d4-4092-92d4-b002f16a00fc", "907df03b-6307-49da-b72c-b7ebcc864fca", "26da464d-c708-4862-ab36-fac43ea0ecfa", "b2e54330-a4e5-464e-a28f-b23c32827954", "9da8acbe-e9a3-4c5b-866a-566f23691260"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_INTERNET_DISCONNECTED\n  (Session info: chrome=123.0.6312.86)\nStacktrace:\n\tGetHandleVerifier [0x00007FF7358A70C2+63090]\n\t(No symbol) [0x00007FF735812D12]\n\t(No symbol) [0x00007FF7356AEC65]\n\t(No symbol) [0x00007FF7356AAC1A]\n\t(No symbol) [0x00007FF73569D514]\n\t(No symbol) [0x00007FF73569E8F8]\n\t(No symbol) [0x00007FF73569D7FF]\n\t(No symbol) [0x00007FF73569D104]\n\t(No symbol) [0x00007FF73569D021]\n\t(No symbol) [0x00007FF73569B0A8]\n\t(No symbol) [0x00007FF73569B8BC]\n\t(No symbol) [0x00007FF7356B14AD]\n\t(No symbol) [0x00007FF735733D67]\n\t(No symbol) [0x00007FF735716FDA]\n\t(No symbol) [0x00007FF735733412]\n\t(No symbol) [0x00007FF735716D83]\n\t(No symbol) [0x00007FF7356E83A8]\n\t(No symbol) [0x00007FF7356E9441]\n\tGetHandleVerifier [0x00007FF735CA262D+4238301]\n\tGetHandleVerifier [0x00007FF735CDF78D+4488509]\n\tGetHandleVerifier [0x00007FF735CD7A6F+4456479]\n\tGetHandleVerifier [0x00007FF735980606+953270]\n\t(No symbol) [0x00007FF73581E5DF]\n\t(No symbol) [0x00007FF7358192B4]\n\t(No symbol) [0x00007FF7358193EB]\n\t(No symbol) [0x00007FF735809C24]\n\tBaseThreadInitThunk [0x00007FFC96F7257D+29]\n\tRtlUserThreadStart [0x00007FFC9920AA58+40]\n\n", "trace": "  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 906, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\owusu\\PycharmProjects\\seleniumFramework\\tests\\conftest.py\", line 48, in setup\n    driver.get(\"https://rahulshettyacademy.com/angularpractice/\")\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 356, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1711968779255, "stop": 1711968781351}, {"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_INTERNET_DISCONNECTED\n  (Session info: chrome=123.0.6312.86)\nStacktrace:\n\tGetHandleVerifier [0x00007FF7358A70C2+63090]\n\t(No symbol) [0x00007FF735812D12]\n\t(No symbol) [0x00007FF7356AEC65]\n\t(No symbol) [0x00007FF7356AAC1A]\n\t(No symbol) [0x00007FF73569D514]\n\t(No symbol) [0x00007FF73569E8F8]\n\t(No symbol) [0x00007FF73569D7FF]\n\t(No symbol) [0x00007FF73569D104]\n\t(No symbol) [0x00007FF73569D021]\n\t(No symbol) [0x00007FF73569B0A8]\n\t(No symbol) [0x00007FF73569B8BC]\n\t(No symbol) [0x00007FF7356B14AD]\n\t(No symbol) [0x00007FF735733D67]\n\t(No symbol) [0x00007FF735716FDA]\n\t(No symbol) [0x00007FF735733412]\n\t(No symbol) [0x00007FF735716D83]\n\t(No symbol) [0x00007FF7356E83A8]\n\t(No symbol) [0x00007FF7356E9441]\n\tGetHandleVerifier [0x00007FF735CA262D+4238301]\n\tGetHandleVerifier [0x00007FF735CDF78D+4488509]\n\tGetHandleVerifier [0x00007FF735CD7A6F+4456479]\n\tGetHandleVerifier [0x00007FF735980606+953270]\n\t(No symbol) [0x00007FF73581E5DF]\n\t(No symbol) [0x00007FF7358192B4]\n\t(No symbol) [0x00007FF7358193EB]\n\t(No symbol) [0x00007FF735809C24]\n\tBaseThreadInitThunk [0x00007FFC96F7257D+29]\n\tRtlUserThreadStart [0x00007FFC9920AA58+40]\n\n", "trace": "  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 906, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\owusu\\PycharmProjects\\seleniumFramework\\tests\\conftest.py\", line 48, in setup\n    driver.get(\"https://rahulshettyacademy.com/angularpractice/\")\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 356, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1711968781523, "stop": 1711968783168}, {"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_INTERNET_DISCONNECTED\n  (Session info: chrome=123.0.6312.86)\nStacktrace:\n\tGetHandleVerifier [0x00007FF7358A70C2+63090]\n\t(No symbol) [0x00007FF735812D12]\n\t(No symbol) [0x00007FF7356AEC65]\n\t(No symbol) [0x00007FF7356AAC1A]\n\t(No symbol) [0x00007FF73569D514]\n\t(No symbol) [0x00007FF73569E8F8]\n\t(No symbol) [0x00007FF73569D7FF]\n\t(No symbol) [0x00007FF73569D104]\n\t(No symbol) [0x00007FF73569D021]\n\t(No symbol) [0x00007FF73569B0A8]\n\t(No symbol) [0x00007FF73569B8BC]\n\t(No symbol) [0x00007FF7356B14AD]\n\t(No symbol) [0x00007FF735733D67]\n\t(No symbol) [0x00007FF735716FDA]\n\t(No symbol) [0x00007FF735733412]\n\t(No symbol) [0x00007FF735716D83]\n\t(No symbol) [0x00007FF7356E83A8]\n\t(No symbol) [0x00007FF7356E9441]\n\tGetHandleVerifier [0x00007FF735CA262D+4238301]\n\tGetHandleVerifier [0x00007FF735CDF78D+4488509]\n\tGetHandleVerifier [0x00007FF735CD7A6F+4456479]\n\tGetHandleVerifier [0x00007FF735980606+953270]\n\t(No symbol) [0x00007FF73581E5DF]\n\t(No symbol) [0x00007FF7358192B4]\n\t(No symbol) [0x00007FF7358193EB]\n\t(No symbol) [0x00007FF735809C24]\n\tBaseThreadInitThunk [0x00007FFC96F7257D+29]\n\tRtlUserThreadStart [0x00007FFC9920AA58+40]\n\n", "trace": "  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 906, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\owusu\\PycharmProjects\\seleniumFramework\\tests\\conftest.py\", line 48, in setup\n    driver.get(\"https://rahulshettyacademy.com/angularpractice/\")\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 356, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1711968785286, "stop": 1711968786913}, {"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_INTERNET_DISCONNECTED\n  (Session info: chrome=123.0.6312.86)\nStacktrace:\n\tGetHandleVerifier [0x00007FF7358A70C2+63090]\n\t(No symbol) [0x00007FF735812D12]\n\t(No symbol) [0x00007FF7356AEC65]\n\t(No symbol) [0x00007FF7356AAC1A]\n\t(No symbol) [0x00007FF73569D514]\n\t(No symbol) [0x00007FF73569E8F8]\n\t(No symbol) [0x00007FF73569D7FF]\n\t(No symbol) [0x00007FF73569D104]\n\t(No symbol) [0x00007FF73569D021]\n\t(No symbol) [0x00007FF73569B0A8]\n\t(No symbol) [0x00007FF73569B8BC]\n\t(No symbol) [0x00007FF7356B14AD]\n\t(No symbol) [0x00007FF735733D67]\n\t(No symbol) [0x00007FF735716FDA]\n\t(No symbol) [0x00007FF735733412]\n\t(No symbol) [0x00007FF735716D83]\n\t(No symbol) [0x00007FF7356E83A8]\n\t(No symbol) [0x00007FF7356E9441]\n\tGetHandleVerifier [0x00007FF735CA262D+4238301]\n\tGetHandleVerifier [0x00007FF735CDF78D+4488509]\n\tGetHandleVerifier [0x00007FF735CD7A6F+4456479]\n\tGetHandleVerifier [0x00007FF735980606+953270]\n\t(No symbol) [0x00007FF73581E5DF]\n\t(No symbol) [0x00007FF7358192B4]\n\t(No symbol) [0x00007FF7358193EB]\n\t(No symbol) [0x00007FF735809C24]\n\tBaseThreadInitThunk [0x00007FFC96F7257D+29]\n\tRtlUserThreadStart [0x00007FFC9920AA58+40]\n\n", "trace": "  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 906, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\owusu\\PycharmProjects\\seleniumFramework\\tests\\conftest.py\", line 48, in setup\n    driver.get(\"https://rahulshettyacademy.com/angularpractice/\")\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 356, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1711968786952, "stop": 1711968788611}, {"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_INTERNET_DISCONNECTED\n  (Session info: chrome=123.0.6312.86)\nStacktrace:\n\tGetHandleVerifier [0x00007FF7358A70C2+63090]\n\t(No symbol) [0x00007FF735812D12]\n\t(No symbol) [0x00007FF7356AEC65]\n\t(No symbol) [0x00007FF7356AAC1A]\n\t(No symbol) [0x00007FF73569D514]\n\t(No symbol) [0x00007FF73569E8F8]\n\t(No symbol) [0x00007FF73569D7FF]\n\t(No symbol) [0x00007FF73569D104]\n\t(No symbol) [0x00007FF73569D021]\n\t(No symbol) [0x00007FF73569B0A8]\n\t(No symbol) [0x00007FF73569B8BC]\n\t(No symbol) [0x00007FF7356B14AD]\n\t(No symbol) [0x00007FF735733D67]\n\t(No symbol) [0x00007FF735716FDA]\n\t(No symbol) [0x00007FF735733412]\n\t(No symbol) [0x00007FF735716D83]\n\t(No symbol) [0x00007FF7356E83A8]\n\t(No symbol) [0x00007FF7356E9441]\n\tGetHandleVerifier [0x00007FF735CA262D+4238301]\n\tGetHandleVerifier [0x00007FF735CDF78D+4488509]\n\tGetHandleVerifier [0x00007FF735CD7A6F+4456479]\n\tGetHandleVerifier [0x00007FF735980606+953270]\n\t(No symbol) [0x00007FF73581E5DF]\n\t(No symbol) [0x00007FF7358192B4]\n\t(No symbol) [0x00007FF7358193EB]\n\t(No symbol) [0x00007FF735809C24]\n\tBaseThreadInitThunk [0x00007FFC96F7257D+29]\n\tRtlUserThreadStart [0x00007FFC9920AA58+40]\n\n", "trace": "  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 906, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\owusu\\PycharmProjects\\seleniumFramework\\tests\\conftest.py\", line 48, in setup\n    driver.get(\"https://rahulshettyacademy.com/angularpractice/\")\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 356, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1711968790702, "stop": 1711968792435}, {"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_INTERNET_DISCONNECTED\n  (Session info: chrome=123.0.6312.86)\nStacktrace:\n\tGetHandleVerifier [0x00007FF7358A70C2+63090]\n\t(No symbol) [0x00007FF735812D12]\n\t(No symbol) [0x00007FF7356AEC65]\n\t(No symbol) [0x00007FF7356AAC1A]\n\t(No symbol) [0x00007FF73569D514]\n\t(No symbol) [0x00007FF73569E8F8]\n\t(No symbol) [0x00007FF73569D7FF]\n\t(No symbol) [0x00007FF73569D104]\n\t(No symbol) [0x00007FF73569D021]\n\t(No symbol) [0x00007FF73569B0A8]\n\t(No symbol) [0x00007FF73569B8BC]\n\t(No symbol) [0x00007FF7356B14AD]\n\t(No symbol) [0x00007FF735733D67]\n\t(No symbol) [0x00007FF735716FDA]\n\t(No symbol) [0x00007FF735733412]\n\t(No symbol) [0x00007FF735716D83]\n\t(No symbol) [0x00007FF7356E83A8]\n\t(No symbol) [0x00007FF7356E9441]\n\tGetHandleVerifier [0x00007FF735CA262D+4238301]\n\tGetHandleVerifier [0x00007FF735CDF78D+4488509]\n\tGetHandleVerifier [0x00007FF735CD7A6F+4456479]\n\tGetHandleVerifier [0x00007FF735980606+953270]\n\t(No symbol) [0x00007FF73581E5DF]\n\t(No symbol) [0x00007FF7358192B4]\n\t(No symbol) [0x00007FF7358193EB]\n\t(No symbol) [0x00007FF735809C24]\n\tBaseThreadInitThunk [0x00007FFC96F7257D+29]\n\tRtlUserThreadStart [0x00007FFC9920AA58+40]\n\n", "trace": "  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 906, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\owusu\\PycharmProjects\\seleniumFramework\\tests\\conftest.py\", line 48, in setup\n    driver.get(\"https://rahulshettyacademy.com/angularpractice/\")\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 356, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1711968792474, "stop": 1711968794249}, {"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_INTERNET_DISCONNECTED\n  (Session info: chrome=123.0.6312.86)\nStacktrace:\n\tGetHandleVerifier [0x00007FF7358A70C2+63090]\n\t(No symbol) [0x00007FF735812D12]\n\t(No symbol) [0x00007FF7356AEC65]\n\t(No symbol) [0x00007FF7356AAC1A]\n\t(No symbol) [0x00007FF73569D514]\n\t(No symbol) [0x00007FF73569E8F8]\n\t(No symbol) [0x00007FF73569D7FF]\n\t(No symbol) [0x00007FF73569D104]\n\t(No symbol) [0x00007FF73569D021]\n\t(No symbol) [0x00007FF73569B0A8]\n\t(No symbol) [0x00007FF73569B8BC]\n\t(No symbol) [0x00007FF7356B14AD]\n\t(No symbol) [0x00007FF735733D67]\n\t(No symbol) [0x00007FF735716FDA]\n\t(No symbol) [0x00007FF735733412]\n\t(No symbol) [0x00007FF735716D83]\n\t(No symbol) [0x00007FF7356E83A8]\n\t(No symbol) [0x00007FF7356E9441]\n\tGetHandleVerifier [0x00007FF735CA262D+4238301]\n\tGetHandleVerifier [0x00007FF735CDF78D+4488509]\n\tGetHandleVerifier [0x00007FF735CD7A6F+4456479]\n\tGetHandleVerifier [0x00007FF735980606+953270]\n\t(No symbol) [0x00007FF73581E5DF]\n\t(No symbol) [0x00007FF7358192B4]\n\t(No symbol) [0x00007FF7358193EB]\n\t(No symbol) [0x00007FF735809C24]\n\tBaseThreadInitThunk [0x00007FFC96F7257D+29]\n\tRtlUserThreadStart [0x00007FFC9920AA58+40]\n\n", "trace": "  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 906, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\owusu\\PycharmProjects\\seleniumFramework\\tests\\conftest.py\", line 48, in setup\n    driver.get(\"https://rahulshettyacademy.com/angularpractice/\")\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 356, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\owusu\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1711968794300, "stop": 1711968796013}], "start": 1711968794300, "stop": 1711968800098}